#!/usr/bin/env python3
"""Stage an app's AppDir from its manifest.

Run by tools/appimage/build.sh inside the flipctl-bundle container, after the cross
build has produced the binary. Everything here is file handling: the manifest is
read with tomllib, the AppDir is laid out, and appimagetool packs it afterwards.

    bundle.py stage APP_DIR APPDIR --binary FILE --version TEXT [--repo DIR]

The AppDir root carries what flipctl reads (app.toml, the icon) and what AppImage
tooling expects (AppRun, a .desktop, .DirIcon), and usr/ carries the program.
"""

import argparse
import os
import shutil
import stat
import sys
import tomllib
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent

# The keys flipctl's own scanner reads, written back verbatim into the bundle.
STRING_KEYS = ("name", "icon", "wayland", "size", "rotate", "runtime", "provides")
BOOL_KEYS = ("audio", "status")
LIST_KEYS = ("apt", "env")


def load_manifest(app_dir: Path) -> dict:
    """The app's own app.toml, as TOML."""
    with open(app_dir / "app.toml", "rb") as f:
        return tomllib.load(f)


def crate_name(app_dir: Path) -> str | None:
    """The binary a Rust app builds, from its crate's name. None for another kind."""
    cargo = app_dir / "Cargo.toml"
    if not cargo.is_file():
        return None
    with open(cargo, "rb") as f:
        return tomllib.load(f)["package"]["name"]


def kind_of(app_dir: Path, manifest: dict) -> str:
    """What kind of app this is, by what the directory holds.

    A crate is built and its binary staged; a directory with an AppRun of its own is
    staged as it stands, which is what a runtime bundle is: files, a pinned wheel and
    a pinned uv, with no compiling anywhere.
    """
    if crate_name(app_dir):
        return "rust"
    if (app_dir / "AppRun").is_file():
        return "staged"
    return "unknown"


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_toml(pairs: list[tuple[str, object]], header: str) -> str:
    """A manifest as flipctl reads it: one key per line at column zero, strings in
    double quotes, lists on one line. tomllib has no writer, and this is every shape
    the manifest has."""
    lines = [f"# {header}"]
    for key, value in pairs:
        if isinstance(value, bool):
            lines.append(f"{key} = {'true' if value else 'false'}")
        elif isinstance(value, str):
            lines.append(f"{key} = {toml_string(value)}")
        elif isinstance(value, list):
            lines.append(f"{key} = [{', '.join(toml_string(v) for v in value)}]")
        else:
            raise TypeError(f"{key}: {type(value).__name__} has no place in a manifest")
    return "\n".join(lines) + "\n"


def derive_manifest(manifest: dict, icon: str, source: str, version: str) -> str:
    """The app.toml the bundle carries: the same manifest with `wayland` pointing at
    AppRun and `icon` at the file beside it. `pip` and any `[bundle]` table are the
    build's business and do not travel."""
    pairs: list[tuple[str, object]] = []
    for key in STRING_KEYS:
        if key == "wayland":
            pairs.append((key, "./AppRun"))
        elif key == "icon":
            pairs.append((key, icon))
        elif key in manifest:
            pairs.append((key, str(manifest[key])))
    for key in BOOL_KEYS:
        if key in manifest:
            pairs.append((key, bool(manifest[key])))
    for key in LIST_KEYS:
        if manifest.get(key):
            pairs.append((key, [str(v) for v in manifest[key]]))
    return emit_toml(pairs, f"Generated by tools/appimage from {source} at {version}. Do not edit.")


def desktop_entry(app_id: str, name: str, version: str) -> str:
    """What appimagetool insists on, and what generic tools read. X- keys are the only
    custom ones desktop-file-validate allows."""
    return "\n".join(
        [
            "[Desktop Entry]",
            "Type=Application",
            f"Name={name}",
            "Exec=AppRun",
            f"Icon={app_id}",
            "Categories=Utility;",
            "Terminal=false",
            f"X-AppImage-Version={version}",
            f"X-FlipCTL-App={app_id}",
            "X-FlipCTL-Manifest=app.toml",
        ]
    ) + "\n"


def render_apprun(command: str) -> str:
    return (HERE / "AppRun.in").read_text().replace("@COMMAND@", command)


def copy_licenses(repo: Path, app_dir: Path, doc: Path, program: str) -> None:
    """What a distribution has to carry: the crate attributions generated for this
    app, our own license, the texts REUSE points at, and the three fonts' terms, since
    their glyphs are compiled into the binary."""
    doc.mkdir(parents=True, exist_ok=True)
    third_party = app_dir / "THIRD-PARTY-LICENSES.md"
    if third_party.is_file():
        shutil.copy2(third_party, doc / third_party.name)
    else:
        print(f"warning: {third_party} missing; run scripts/gen-third-party-licenses.sh", file=sys.stderr)
    shutil.copy2(repo / "LICENSE", doc / "LICENSE")
    texts = repo / "LICENSES"
    if texts.is_dir():
        (doc / "LICENSES").mkdir(exist_ok=True)
        for text in sorted(texts.glob("*.txt")):
            shutil.copy2(text, doc / "LICENSES" / text.name)
    for font in sorted((repo / "third_party" / "flipctl-fonts").glob("*/")):
        for terms in sorted(font.glob("LICENSE*")):
            target = doc / "fonts" / font.name
            target.mkdir(parents=True, exist_ok=True)
            shutil.copy2(terms, target / terms.name)


def stage_staged(app_dir: Path, appdir: Path, tools: Path) -> None:
    """A runtime bundle: its own AppRun, its own Python, and the pieces it carries.

    The Slint binding and the widget sources are what make a script able to draw, and
    uv is what reads the dependencies a script declares. Both are pinned in
    tools.lock and fetched by build.sh, so this only copies.
    """
    lib = appdir / "usr" / "lib" / "python"
    lib.mkdir(parents=True)
    (appdir / "usr" / "bin").mkdir(parents=True)

    shutil.copy2(app_dir / "AppRun", appdir / "AppRun")
    os.chmod(appdir / "AppRun", 0o755)
    for name in ("launcher.py",):
        shutil.copy2(app_dir / name, lib / name)
    shutil.copytree(app_dir / "flipctl", lib / "flipctl")

    wheel = tools / "slint-wheel"
    with zipfile.ZipFile(wheel) as z:
        z.extractall(lib)
    # The wheel ships the extension without the bit that says it may be executed, and
    # a shared object still has to be loadable from a read-only squashfs.
    for so in lib.rglob("*.so*"):
        os.chmod(so, 0o755)

    shutil.copy2(tools / "uv.bin", appdir / "usr" / "bin" / "uv")
    os.chmod(appdir / "usr" / "bin" / "uv", 0o755)


def stage_ui(repo: Path, appdir: Path) -> None:
    """The widget library as a script's compiler sees it.

    The same `.slint` files flipctl and every Rust app compile, the theme generated
    from tokens.toml, and the three fonts at the relative path `fonts.slint` imports
    them by. Laid out as they are in the repository, because those imports are
    relative and a flatter tree would not resolve.
    """
    ui = appdir / "usr" / "share" / "flipctl-ui"
    shutil.copytree(repo / "crates/flipper-ui/ui", ui / "crates/flipper-ui/ui")
    shutil.copytree(repo / "crates/flipctl-app/ui", ui / "crates/flipctl-app/ui")
    shutil.copytree(
        repo / "third_party/flipctl-fonts",
        ui / "third_party/flipctl-fonts",
        ignore=shutil.ignore_patterns("*.glyphs"),
    )
    theme = next((repo / "target").rglob("build/flipper-ui-*/out/theme.slint"), None)
    if theme is None:
        sys.exit("no generated theme.slint under target/; build flipper-ui first")
    shutil.copy2(theme, ui / "theme.slint")


def stage(app_dir: Path, appdir: Path, binary: Path | None, version: str, repo: Path) -> None:
    manifest = load_manifest(app_dir)
    kind = kind_of(app_dir, manifest)
    if kind == "unknown":
        sys.exit(f"{app_dir}: neither a crate nor an AppRun, so there is nothing to bundle")
    app_id = app_dir.name
    program = crate_name(app_dir) or app_id
    if appdir.exists():
        shutil.rmtree(appdir)

    if kind == "rust":
        (appdir / "usr" / "bin").mkdir(parents=True)
        shutil.copy2(binary, appdir / "usr" / "bin" / program)
        os.chmod(appdir / "usr" / "bin" / program, 0o755)
        apprun = appdir / "AppRun"
        apprun.write_text(render_apprun(f'"$APPDIR/usr/bin/{program}" "$@"'))
        os.chmod(apprun, 0o755)
    else:
        stage_staged(app_dir, appdir, repo / "target/appimage/tools")
        stage_ui(repo, appdir)

    icon_name = f"{app_id}.png"
    source_icon = app_dir / manifest["icon"] if manifest.get("icon") else HERE / "flipctl.png"
    shutil.copy2(source_icon, appdir / icon_name)

    (appdir / "app.toml").write_text(
        derive_manifest(manifest, icon_name, f"apps/{app_id}/app.toml", version)
    )
    (appdir / f"{app_id}.desktop").write_text(
        desktop_entry(app_id, manifest.get("name", app_id), version)
    )
    copy_licenses(repo, app_dir, appdir / "usr" / "share" / "doc" / program, program)
    if kind == "staged":
        # What the bundle carries, beside our own terms: the binding is Slint's, under
        # the same tri-license the Rust one is taken under, and uv is Apache-2.0/MIT.
        for name in ("slint-1.17.1b2.dist-info", "uv"):
            src = appdir / "usr/lib/python" / name
            if src.is_dir():
                shutil.copytree(
                    src, appdir / "usr/share/doc" / program / name,
                    ignore=shutil.ignore_patterns("RECORD", "WHEEL", "*.py"),
                    dirs_exist_ok=True,
                )
    check_appdir(appdir)


def check_appdir(appdir: Path) -> None:
    """The invariants appimagetool and flipctl each rely on, failed loudly here rather
    than found on the device."""
    problems = []
    apprun = appdir / "AppRun"
    if not apprun.is_file() or not apprun.stat().st_mode & stat.S_IXUSR:
        problems.append("AppRun missing or not executable")
    if not (appdir / "app.toml").is_file():
        problems.append("no app.toml at the root")
    desktops = list(appdir.glob("*.desktop"))
    if len(desktops) != 1:
        problems.append(f"{len(desktops)} .desktop files, want one")
    elif "Exec=AppRun" not in desktops[0].read_text():
        problems.append(f"{desktops[0].name} does not Exec=AppRun")
    if not list(appdir.glob("*.png")):
        problems.append("no icon at the root")
    if (appdir / "Cargo.toml").exists():
        problems.append("Cargo.toml travelled; flipctl would take the bundle for a crate")
    if list(appdir.rglob("__pycache__")) or list(appdir.rglob("*.pyc")):
        problems.append("bytecode travelled; it is this host's, not the device's")
    for path in appdir.rglob("*"):
        if path.is_symlink() and os.readlink(path).startswith("/"):
            problems.append(f"absolute symlink: {path.relative_to(appdir)}")
    if problems:
        sys.exit("AppDir is not right:\n  " + "\n  ".join(problems))


def main(argv: list[str]) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    st = sub.add_parser("stage", help="lay out an AppDir from an app directory")
    st.add_argument("app_dir", type=Path)
    st.add_argument("appdir", type=Path)
    st.add_argument("--binary", type=Path, help="the cross-built program, for a crate")
    st.add_argument("--version", required=True, help="what X-AppImage-Version says")
    st.add_argument("--repo", type=Path, default=HERE.parent.parent, help="the repository root, for the licenses")
    args = parser.parse_args(argv)
    if args.command == "stage":
        stage(args.app_dir, args.appdir, args.binary, args.version, args.repo)


if __name__ == "__main__":
    main(sys.argv[1:])
