#!/bin/bash
# Lay the built apps out as a folder flipctl can read, and write the catalogue index
# that offers them.
#
# Usage:
#   tools/appimage/stage.sh <dest> [base-url]
#
# The bundles have to be built already; this only arranges them. What comes out is
# exactly what flipctl walks: an AppImage per app, under the folder its manifest asks
# for, the script apps at the path they sit at in apps/, and a folder's icon.png
# beside them. Nothing ships in the image any more, so this tree is the catalogue
# repository's content and `apps.toml` at its root is what a device reads to know what
# it can install.
#
# The index is generated rather than kept by hand because every field in it is already
# written down somewhere: the name and the runtime in the app's own manifest, the size
# and the checksum in the file itself. A hand-maintained list of sha256s is a list that
# goes wrong silently.
#
# `base-url` is where the bytes are served from, which is not where this tree is: the
# index can sit in git while the files are release assets, and since release assets are
# a flat namespace the url is the base and the file's own name, never its folder.
#
# What counts as an app is decided the way flipctl decides it, so nothing here has a
# list to keep up to date:
#
#   * an AppImage in target/appimage, named after the directory under apps/ it was
#     built from, which is where its manifest and its `folder` are read from
#   * any file whose head carries a `/// flipctl` block, whatever its extension, as
#     long as no directory above it holds an app.toml: those are a bundle's own
#     sources, not apps
#   * icon.png in a folder, which is that folder's own icon and has no block to be
#     found by. It is staged but not offered: it belongs to a folder rather than to an
#     app, and there is nothing to press Install on
set -euo pipefail

HERE=$(cd "$(dirname "$0")/../.." && pwd)
BUILT="$HERE/target/appimage"

[ $# -ge 1 ] && [ $# -le 2 ] || { sed -n '2,6p' "$0"; exit 2; }
DEST=$1
BASE=${2:-https://github.com/flipperdevices/flipctl-apps/releases/download/apps}
INDEX="$DEST/apps.toml"

# A key's value out of a manifest: column zero, double quoted, first one wins, which is
# how flipctl's own reader takes it.
key_of() {
    sed -n "s/^$2 *= *\"\([^\"]*\)\".*/\1/p" <<<"$1" | head -n1
}

# The `/// flipctl` block out of a script's head, with the comment marker stripped, so
# the same reader works on it as on an app.toml.
block_of() {
    head -c 8192 "$1" | awk '
        /\/\/\/[ \t]*flipctl[ \t]*$/ { inside = 1; next }
        inside && /^[ \t]*(#|\/\/|--)[ \t]*\/\/\/[ \t]*$/ { exit }
        inside { sub(/^[ \t]*(#|\/\/|--)[ \t]?/, ""); print }
    '
}

# The folder an app asks to be filed under, from the source manifest: a bundle carries
# only the keys flipctl itself reads, and this is the installer's business.
folder_of() {
    key_of "$(cat "$HERE/apps/$1/app.toml" 2>/dev/null)" folder
}

# Whether any directory at or above this one holds a manifest, which makes the file a
# bundle's source rather than an app in its own right.
inside_a_bundle() {
    local dir=$1
    while [ "$dir" != "." ] && [ "$dir" != "/" ]; do
        [ -e "$HERE/apps/$dir/app.toml" ] && return 0
        dir=$(dirname "$dir")
    done
    return 1
}

# One `[[app]]` table. The checksum comes from the sidecar the build already wrote
# where there is one, and is computed where there is not, which is every script.
offer() {
    local path=$1 file=$2 name=$3 runtime=$4 provides=$5 size sha
    size=$(stat -c %s "$file")
    if [ -e "$file.sha256" ]; then
        sha=$(cut -d' ' -f1 <"$file.sha256")
    else
        sha=$(sha256sum "$file" | cut -d' ' -f1)
    fi
    {
        echo
        echo "[[app]]"
        echo "name = \"$name\""
        echo "path = \"$path\""
        echo "url = \"$BASE/$(basename "$path")\""
        if [ -n "$runtime" ]; then echo "runtime = \"$runtime\""; fi
        if [ -n "$provides" ]; then echo "provides = \"$provides\""; fi
        echo "size = $size"
        echo "sha256 = \"$sha\""
    } >>"$INDEX"
}

mkdir -p "$DEST"
cat >"$INDEX" <<EOF
# What a Flipper One can install, read by the app manager.
#
# Generated by tools/appimage/stage.sh. Every field here is already written down in the
# app's own manifest or in the file itself, so edit those and stage again rather than
# editing this.
EOF

staged=0
offered=0
for image in "$BUILT"/*.AppImage; do
    [ -e "$image" ] || continue
    name=$(basename "$image")
    app=${name%-aarch64.fap.AppImage}
    manifest=$(cat "$HERE/apps/$app/app.toml" 2>/dev/null || true)
    folder=$(key_of "$manifest" folder)
    mkdir -p "$DEST${folder:+/$folder}"
    install -m 755 "$image" "$DEST${folder:+/$folder}/$name"
    offer "${folder:+$folder/}$name" "$image" \
        "$(key_of "$manifest" name)" "" "$(key_of "$manifest" provides)"
    echo "stage: $name${folder:+ in $folder}"
    staged=$((staged + 1))
    offered=$((offered + 1))
done

# The scripts and the folder icons, at the path they already sit at.
while IFS= read -r rel; do
    dir=$(dirname "$rel")
    inside_a_bundle "$dir" && continue
    icon=false
    [ "$(basename "$rel")" = icon.png ] && icon=true
    if [ "$icon" = false ] && ! head -c 8192 "$HERE/apps/$rel" | grep -q "/// flipctl"; then
        continue
    fi
    mkdir -p "$DEST/$dir"
    install -m 644 "$HERE/apps/$rel" "$DEST/$rel"
    echo "stage: $rel"
    staged=$((staged + 1))
    if [ "$icon" = false ]; then
        block=$(block_of "$HERE/apps/$rel")
        # A script with no `runtime` of its own asks for its extension, which is the
        # rule flipctl applies when it reads the same block.
        runtime=$(key_of "$block" runtime)
        [ -n "$runtime" ] || runtime=${rel##*.}
        offer "$rel" "$HERE/apps/$rel" "$(key_of "$block" name)" \
            "$runtime" "$(key_of "$block" provides)"
        offered=$((offered + 1))
    fi
done < <(cd "$HERE/apps" && find . -type f -not -path "*/__pycache__/*" -not -path "*/target/*" \
    -printf '%P\n' | sort)

# A script app is only startable if something provides its runtime, and a staging with
# no bundles at all means build.sh was never run.
[ "$staged" -gt 0 ] || { echo "stage: nothing to stage; run tools/appimage/build.sh --all first" >&2; exit 1; }
echo "stage: $staged files in $DEST, $offered offered in apps.toml"
