//! Shared UI component library for the Flipper One 256x144 SPI panel.
//!
//! Three consumers: flipperos-installer (size-critical, maskrom-loaded),
//! flipper-boot-menu (Falcon initramfs) and flipctl, the system launcher.

pub mod app;
pub mod boot;
pub mod boot_menu;
pub mod font;
pub mod key;
pub mod keyboard;
pub mod layout;
pub mod log;
pub mod net;
pub mod old_flipctl_loader;
pub mod status;
pub mod switcher;
pub mod sysinfo;
pub mod watch;
pub mod wifi;
pub mod paint;
pub mod pixel;
pub mod platform;
#[cfg(feature = "device")]
pub mod evdev;
#[cfg(feature = "device")]
pub mod kms;
#[cfg(feature = "remote")]
pub mod remote;
pub mod scale;
#[cfg(feature = "gpu")]
pub mod gpu;
#[cfg(feature = "wayland")]
pub mod sway;
#[cfg(feature = "wayland")]
pub mod wl;
#[cfg(feature = "wayland")]
pub mod wl_sink;
#[cfg(feature = "slint")]
pub mod slint_render;

/// The compiled .slint components.
///
/// Generated by slint-build from `ui/`, re-exported here so binaries do not each
/// have to run the compiler. Behind `screens`, because this is Root and every
/// screen with it: a consumer that needs one screen compiles its own entry file
/// against `ui/` instead and takes only `slint`.
#[cfg(feature = "screens")]
pub mod ui {
    slint::include_modules!();
}

/// Design tokens, generated from tokens.toml at build time.
#[allow(dead_code)]
pub mod theme {
    include!(concat!(env!("OUT_DIR"), "/theme.rs"));
}

pub use app::{AppEntry, Rotate};
pub use font::BitmapFont;
pub use key::{FlipperKey, KeyEvent};
pub use paint::Surface;
pub use status::{Ethernet, Status, StatusSource};
pub use platform::{Frame, FrameSink, InputSource};
pub use pixel::{Gray8, Rect};
pub use theme::{PANEL_H, PANEL_W};
